version: '3.3'
services:
  database:
    image: 'mongo:latest'
    restart: always
    container_name: 'codmongo'
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
  rabbitmq:
    container_name: 'codmq'
    restart: always
    image: 'rabbitmq:management'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
  node-api:
    container_name: 'codapi'
    build: ./../api/packages/search
    environment:
      - NODE_ENV=prod
    ports:
      - '5000:5000'
    depends_on:
      - database
      - rabbitmq
    links:
      - database
      - rabbitmq
    command: 'yarn start:prod'
  node-micro:
    container_name: 'codmicro1'
    build: ./../api/packages/translate
    environment:
      - NODE_ENV=prod
    depends_on:
      - database
      - rabbitmq
      - node-api
    links:
      - database
      - rabbitmq
      - node-api
    command: 'yarn start:prod'
  dependencies:
    container_name: 'coddep'
    image: dadarek/wait-for-dependencies
    depends_on:
      - database
      - rabbitmq
      - node-api
      - node-micro
    command: rabbitmq:15672
  webapp:
    container_name: codapp
    build: ./../client
    ports:
      - '8080:80'
    depends_on:
      - dependencies
      - database
      - rabbitmq
      - node-api
      - node-micro
