version: '3.3'
services:
  database:
    image: 'mongo:latest'
    restart: always
    container_name: 'codmongo'
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
  rabbitmq:
    container_name: 'codmq'
    restart: always
    image: 'rabbitmq:management'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
  node-api:
    container_name: 'codapi'
    image: 'node:8'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./../api/packages/search:/home/node/app
    ports:
      - '5000:5000'
    depends_on:
      - database
      - rabbitmq
    links:
      - database
      - rabbitmq
    command: 'npm start'
  node-micro:
    container_name: 'codmicro1'
    image: 'node:8'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./../api/packages/translate:/home/node/app
    depends_on:
      - database
      - rabbitmq
      - node-api
    links:
      - database
      - rabbitmq
      - node-api
    command: 'npm start'
